version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airbnb_user
      POSTGRES_PASSWORD: airbnb_password
      POSTGRES_DB: airbnb_clone
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:




